config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations' } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  get 'toppages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show]
  get '/users/:id/a', to:'users#answers', as: 'users_a'
  get '/users/:id/q', to:'users#questions', as: 'users_q'
  get '/users/:id/fav', to:'users#favorites', as: 'users_f'
  get '/questions', to:'questions#index'
  get '/q/new', to: 'questions#new'
  post '/q/confirm', to: 'questions#confirm'
  post '/q', to: 'questions#create', as: 'qs'
  get '/q/:id', to: 'questions#show', as: 'q_show'
  get '/q/edit/:id', to: 'questions#edit', as: 'q_edit'
  patch '/q/edit/:id', to: 'questions#update', as: 'q_update'
  delete '/q/:id', to: 'questions#destroy', as: 'q_destroy'
  # get '/a', to:'answers#index'
  get '/:id/a', to: 'answers#new', as: 'a_new'
  post '/:id/a_confirm', to: 'answers#confirm', as: 'a_confirm'
  post '/:id/a', to: 'answers#create', as: 'a_create'
  get '/a/:id', to: 'answers#show', as: 'a_show'
  get '/a/edit/:id', to: 'answers#edit', as: 'a_edit'
  patch '/a/edit/:id', to: 'answers#update', as: 'a_update'
  delete '/a/:id', to: 'answers#destroy', as: 'a_destroy'
  # post '/a/:id/favorites', to: 'favorites#create', as: 'favorite_create'
  # delete '/a/:id/favorites', to: 'favorites#destroy', as: 'favorite_destroy'
  resources :answers, only: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/question.rb
class Question < ApplicationRecord
  acts_as_taggable
  generate_public_uid
  belongs_to :user, optional: true
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { maximum: 50 }
  validates :content_1, presence: true
  validates :content_2, presence: true
  validates :content_3, presence: true
  with_options length: { maximum: 255 } do
    validates :content_1
    validates :content_2
    validates :content_3
    validates :content_4
    validates :content_5
    validates :content_6
    validates :content_7
    validates :content_8
    validates :content_9
    validates :content_10
    validates :content_11
    validates :content_12
    validates :content_13
    validates :content_14
    validates :content_15
    validates :content_16
    validates :content_17
    validates :content_18
    validates :content_19
    validates :content_20
    validates :content_21
    validates :content_22
    validates :content_23
    validates :content_24
    validates :content_25
    validates :content_26
    validates :content_27
    validates :content_28
    validates :content_29
    validates :content_30
    validates :content_31
    validates :content_32
    validates :content_33
    validates :content_34
    validates :content_35
    validates :content_36
    validates :content_37
    validates :content_38
    validates :content_39
    validates :content_40
    validates :content_41
    validates :content_42
    validates :content_43
    validates :content_44
    validates :content_45
    validates :content_46
    validates :content_47
    validates :content_48
    validates :content_49
    validates :content_50
    validates :content_51
    validates :content_52
    validates :content_53
    validates :content_54
    validates :content_55
    validates :content_56
    validates :content_57
    validates :content_58
    validates :content_59
    validates :content_60
    validates :content_61
    validates :content_62
    validates :content_63
    validates :content_64
    validates :content_65
    validates :content_66
    validates :content_67
    validates :content_68
    validates :content_69
    validates :content_70
    validates :content_71
    validates :content_72
    validates :content_73
    validates :content_74
    validates :content_75
    validates :content_76
    validates :content_77
    validates :content_78
    validates :content_79
    validates :content_80
    validates :content_81
    validates :content_82
    validates :content_83
    validates :content_84
    validates :content_85
    validates :content_86
    validates :content_87
    validates :content_88
    validates :content_89
    validates :content_90
    validates :content_91
    validates :content_92
    validates :content_93
    validates :content_94
    validates :content_95
    validates :content_96
    validates :content_97
    validates :content_98
    validates :content_99
    validates :content_100
  end
  
  def to_param
    public_uid
  end
  

  ransacker :reply_count do
    query = '(SELECT COUNT(answers.question_id) FROM answers where answers.question_id = questions.id GROUP BY answers.question_id)'
    Arel.sql(query)
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :q_find, only: [:show, :edit, :update, :destroy]
  before_action :q_content_post_set, only: [:show, :edit, :update]
  before_action :content_set
  
  def index
    @search = Question.ransack(params[:q])
    @qs = @search.result.page(params[:page]).per(12)
  end

  def show
  end

  def new
    if user_signed_in?
      @q = current_user.questions.new
      q_initial_content_post_set
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    q_initial_content_post_set
    if @q.user == current_user
      unless user_signed_in?
        redirect_to new_user_session_path
      end
    else
      redirect_to root_path
    end
  end

  def update
    q_initial_content_post_set
    if @q.update_attributes(q_params)
      redirect_to q_show_url(@q)
    else
      render :edit
    end
  end

  def destroy
    if @q.user == current_user
      @q.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end


 # def confirm
  #   @q = current_user.questions.new(q_params)
  #   q_content_post_set
  #   q_initial_content_post_set
  #   render :new if @q.invalid?
  # end

  def create
    @q = current_user.questions.new(q_params)
    q_initial_content_post_set
    if params[:back].present?
      render :new
      return
    end

    if @q.save
      flash[:success] = 'あるあるを投稿しました。'
      redirect_to q_show_url(@q)
    else
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render :new
    end
  end

  def res

  end

  private
  def q_params
    params.require(:question).permit(:title, @content_array, :tag_list)
  end

  def q_find
    @q = Question.find_by(public_uid: params[:id])
  end
  
end

app/views/questions/confirm.html.slim
.container
  = form_for @q, url: qs_path do |f|
    .row
      .col-md-10.offset-md-1.form-group
        h2.text-center 投稿確認
        .border-bottom(style="margin: 10px 0;")
        p
         b タイトル
        h4 = @q.title
        =f.hidden_field :title
        .border-bottom(style="margin: 10px 0;")
        - @q_content_post.each_with_index do |x, i|
          p
            b 質問#{i+1}
          p = x
          .border-bottom(style="margin: 10px 0;")
        - @content_array.each do |x|
          = f.hidden_field x
        - if @q.tag_list.present?
          p
            b タグ
          h5.mb-5
            - @q.tag_list.each do |tag|
              span.badge.badge-primary.mr-2
                = tag      
              = f.hidden_field :tag_list, value: @q.tag_list.join(',')
        = f.submit '戻る', name: 'back', class: 'btn btn-secondary btn-lg mr-3'
        = f.submit '投稿', class: 'btn btn-success btn-lg'

app/views/questions/edit.html.slim
#App.container
  = form_with model: @q, local: true, url: q_update_path do |f|
    = render 'layouts/error_messages', model: f.object 
    .row
      .col-md-10.offset-md-1.form-group
        .row
          .col-md-2
            = f.label :title, 'タイトル'
            small
              span.badge.badge-danger 必須
          .col-md-10
            = f.text_field :title, class: 'form-control', "v-model" => "title"
            text-count :text="title" :limit="50"
            p#initial_title(style="display: none;") = @q.title
          / content開始
          - @content_array.each_with_index do |x, i|
            template v-if="#{i} < fieldCount"
              .col-12.border-bottom.article-border
              .col-md-2
                = f.label x, "質問#{i+1}"
                - if i < 3
                  small
                    span.badge.badge-danger 必須
              .col-md-10    
                = f.text_area x, class: 'form-control', "v-model" => "content[#{i}]"
                text-count :text="content[#{i}]" :limit="255"
          / contentここまで
          - if @q_content_post.present?
            .initial_content
              - @q_initial_content_post.each_with_index do |x, i|
                p id="initial_content_#{i}" style="display: none;" = x
          .col-12.border.bg-light.p-1.rounded.text-center.d-flex.justify-content-around.mb-3
            span.my-auto 質問を追加
            button.btn.btn-info.col-3.ml-2 type="button" v-on:click="fieldCount++" +1
            button.btn.btn-info.col-3.ml-2 type="button" v-on:click="fieldCount += 5" +5
            button.btn.btn-info.col-3.ml-2 type="button" v-on:click="fieldCount += 10" +10
          .col-md-2
            = f.label :tag_list, 'タグ'
          .col-md-10
            = f.text_field :tag_list, value: @q.tag_list.join(','), class: "form-control"
            small 半角コンマで区切って入力(例：ゲーム,アニメ,キャラクター)
          .col-12.mt-3
            = f.submit "投稿する", class:"btn btn-secondary btn-block mb-3"
        .text-right.mt-5
          = link_to "質問を削除する", q_destroy_path, method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-outline-danger btn-sm"
              
= javascript_pack_tag 'q_new'

app/views/questions/index.html.slim
.container
    .row
        .col-md-10.offset-md-1
            .row
                .col-md-4.order-md-2.text-right.text-nowrap.mb-4
                    span.btn-group.mr-3
                        - if params.dig(:q, :created_at_gteq).present?
                            = link_to '最近',{:controller=>"questions",:action=>"index",:q=>{:created_at_gteq => 30.day.ago.all_day, :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :sorts => params.dig(:q, :sorts)}}, class:'btn btn-info'
                            = link_to '全部',{:controller=>"questions",:action=>"index",:q=>{:created_at_gteq => '', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :sorts => params.dig(:q, :sorts)}}, class:'btn btn-outline-info'
                        - else
                            = link_to '最近',{:controller=>"questions",:action=>"index",:q=>{:created_at_gteq => 30.day.ago.all_day, :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :sorts => params.dig(:q, :sorts)}}, class:'btn btn-outline-info'
                            = link_to '全部',{:controller=>"questions",:action=>"index",:q=>{:created_at_gteq => '', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :sorts => params.dig(:q, :sorts)}}, class:'btn btn-info'
                    span.btn-group
                        - if params.dig(:q, :sorts) === 'reply_count desc'
                            = link_to '人気順',{:controller=>"questions",:action=>"index",:q=>{:sorts => 'reply_count desc', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont),:created_at_gteq => params.dig(:q, :created_at_gteq)}}, class:'btn btn-info'
                            = link_to '新着順',{:controller=>"questions",:action=>"index",:q=>{:sorts => 'id desc', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :created_at_gteq => params.dig(:q, :created_at_gteq)}}, class:'btn btn-outline-info'
                        - else
                            = link_to '人気順',{:controller=>"questions",:action=>"index",:q=>{:sorts => 'reply_count desc', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont),:created_at_gteq => params.dig(:q, :created_at_gteq)}}, class:'btn btn-outline-info'
                            = link_to '新着順',{:controller=>"questions",:action=>"index",:q=>{:sorts => 'id desc', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :created_at_gteq => params.dig(:q, :created_at_gteq)}}, class:'btn btn-info'
                .col-md-8.order-md-1.mb-4
                    = search_form_for @search, url:questions_path do |f|
                        = f.search_field :created_at_gteq, value: params.dig(:q, :created_at_gteq), class: 'form-control', style: 'display: none;'
                        = f.search_field :sorts, value: params.dig(:q, :sorts), class: 'form-control', style: 'display: none;'
                        .input-group
                            = f.search_field :title_or_tags_name_cont, value: params.dig(:q, :title_or_tags_name_cont), class: 'form-control'
                            span.input-group-btn
                                = f.submit '検索', class: 'btn btn-info'
            == render './posts/q_posts', posts: @qs
            - unless @qs.present?
                .alert.alert-secondary 検索結果はありませんでした
            .border-bottom.article-border.mt-3.mb-5
            = paginate @qs

app/views/questions/new.html.slim
#App.container
  = form_with model: @q, local: true, url: q_confirm_path do |f|
    = render 'layouts/error_messages', model: f.object 
    .row
      .col-md-10.offset-md-1.form-group
        .row
          .col-md-2
            = f.label :title, 'タイトル'
            small
              span.badge.badge-danger 必須
          .col-md-10
            = f.text_field :title, class: 'form-control', "v-model" => "title"
            text-count :text="title" :limit="50"
            p#initial_title(style="display: none;") = @q.title
          / content開始
          - @content_array.each_with_index do |x, i|
            template v-if="#{i} < fieldCount"
              .col-12.border-bottom.article-border
              .col-md-2
                = f.label x, "質問#{i+1}"
                - if i < 3
                  small
                    span.badge.badge-danger 必須
              .col-md-10    
                = f.text_area x, class: 'form-control', "v-model" => "content[#{i}]"
                text-count :text="content[#{i}]" :limit="255"
          / contentここまで
          - if @q_content_post.present?
            .initial_content
              - @q_initial_content_post.each_with_index do |x, i|
                p id="initial_content_#{i}" style="display: none;" = x
          .col-12.border.bg-light.p-1.rounded.text-center.d-flex.justify-content-around.mb-3
            span.my-auto 質問を追加
            button.btn.btn-info.col-3.ml-2 type="button" v-on:click="fieldCount++" +1
            button.btn.btn-info.col-3.ml-2 type="button" v-on:click="fieldCount += 5" +5
            button.btn.btn-info.col-3.ml-2 type="button" v-on:click="fieldCount += 10" +10
          .col-md-2
            = f.label :tag_list, 'タグ'
          .col-md-10
            = f.text_field :tag_list, value: @q.tag_list.join(','), class: "form-control"
            small 半角コンマで区切って入力(例：ゲーム,アニメ,キャラクター)
          .col-12.mt-3
            = f.submit "投稿する", class:"btn btn-secondary btn-block mb-3"
              
= javascript_pack_tag 'q_new'

app/views/questions/res.html.slim
aaa

app/views/questions/show.html.slim
- set_meta_tags title: @q.title,
    og: {   site_name: 'intervieeew.net',
            title: @q.title,
            description: [@q.content_1,@q.content_2,@q.content_3,@q.content_4,@q.content_5,@q.content_6,@q.content_7,@q.content_8,@q.content_9,@q.content_10].compact.reject(&:empty?).join(','),
            type: 'website',
            url: request.original_url,
            locale: 'ja_JP'}
.container
    .row
      .col-md-10.offset-md-1
        - if user_signed_in?
                - if current_user.id === @q.user.id
                    .text-right.mb-4
                        = link_to "編集する", q_edit_path(@q.public_uid), class: 'btn btn-outline-secondary'
        .d-flex.justify-content-between.mb-3
          span style="color: green;"
                    i.fas.fa-reply.fa-lg.mr-1
                    = @q.answers.length
          a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false" Tweet
          script[async src="https://platform.twitter.com/widgets.js" charset="utf-8"]
        h2 = @q.title
        .border-bottom.article-border
        - @q_content_post.each_with_index do |x, i|
          div style="word-wrap: break-word;"
            p
              b 質問#{i+1}
            p = x
          .border-bottom.article-border
        -if @q.tag_list.present?
          p.mb-3
            - @q.tag_list.each do |tag|
              = link_to :controller=>"questions",:action=>"index",:q=>{:title_or_tags_name_cont => tag, :sorts => 'id desc'} do
                span.badge.badge-primary.mr-2
                  i.far.fa-question-circle
                  = tag
        .d-flex.justify-content-between.mb-3
          = link_to user_path(@q.user.public_uid)
            p.mb-5 投稿者:#{@q.user.username}
          .text-dark
            i.fas.fa-clock
            = l @q.created_at, format: :long
        = link_to '答える', a_new_path(@q.public_uid), class:'btn btn-lg btn-info btn-block mb-5'
        -if @q.answers.present?
          h3.bg-light この質問に回答した投稿
          == render './posts/a_posts', posts: @q.answers.order('id desc').first(3)