config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations' } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  get 'toppages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show]
  get '/users/:id/a', to:'users#answers', as: 'users_a'
  get '/users/:id/q', to:'users#questions', as: 'users_q'
  get '/users/:id/fav', to:'users#favorites', as: 'users_f'
  get '/questions', to:'questions#index'
  get '/q/new', to: 'questions#new'
  post '/q/confirm', to: 'questions#confirm'
  post '/q', to: 'questions#create', as: 'qs'
  get '/q/:id', to: 'questions#show', as: 'q_show'
  get '/q/edit/:id', to: 'questions#edit', as: 'q_edit'
  patch '/q/edit/:id', to: 'questions#update', as: 'q_update'
  delete '/q/:id', to: 'questions#destroy', as: 'q_destroy'
  # get '/a', to:'answers#index'
  get '/:id/a', to: 'answers#new', as: 'a_new'
  post '/:id/a_confirm', to: 'answers#confirm', as: 'a_confirm'
  post '/:id/a', to: 'answers#create', as: 'a_create'
  get '/a/:id', to: 'answers#show', as: 'a_show'
  get '/a/edit/:id', to: 'answers#edit', as: 'a_edit'
  patch '/a/edit/:id', to: 'answers#update', as: 'a_update'
  delete '/a/:id', to: 'answers#destroy', as: 'a_destroy'
  # post '/a/:id/favorites', to: 'favorites#create', as: 'favorite_create'
  # delete '/a/:id/favorites', to: 'favorites#destroy', as: 'favorite_destroy'
  resources :answers, only: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, optional: true
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy 
  mount_uploader :image, ImageUploader
  acts_as_taggable
  generate_public_uid

  def to_param
    public_uid
  end

  validates :title, presence: true, length: { maximum: 50 }
  validates :answerer, length: { maximum: 10 }
  validates :overview, length: { maximum: 1000 }
  validates :image_or_select, presence: true
  with_options length: { maximum: 255 } do
    validates :content_1
    validates :content_2
    validates :content_3
    validates :content_4
    validates :content_5
    validates :content_6
    validates :content_7
    validates :content_8
    validates :content_9
    validates :content_10
    validates :content_11
    validates :content_12
    validates :content_13
    validates :content_14
    validates :content_15
    validates :content_16
    validates :content_17
    validates :content_18
    validates :content_19
    validates :content_20
    validates :content_21
    validates :content_22
    validates :content_23
    validates :content_24
    validates :content_25
    validates :content_26
    validates :content_27
    validates :content_28
    validates :content_29
    validates :content_30
    validates :content_31
    validates :content_32
    validates :content_33
    validates :content_34
    validates :content_35
    validates :content_36
    validates :content_37
    validates :content_38
    validates :content_39
    validates :content_40
    validates :content_41
    validates :content_42
    validates :content_43
    validates :content_44
    validates :content_45
    validates :content_46
    validates :content_47
    validates :content_48
    validates :content_49
    validates :content_50
    validates :content_51
    validates :content_52
    validates :content_53
    validates :content_54
    validates :content_55
    validates :content_56
    validates :content_57
    validates :content_58
    validates :content_59
    validates :content_60
    validates :content_61
    validates :content_62
    validates :content_63
    validates :content_64
    validates :content_65
    validates :content_66
    validates :content_67
    validates :content_68
    validates :content_69
    validates :content_70
    validates :content_71
    validates :content_72
    validates :content_73
    validates :content_74
    validates :content_75
    validates :content_76
    validates :content_77
    validates :content_78
    validates :content_79
    validates :content_80
    validates :content_81
    validates :content_82
    validates :content_83
    validates :content_84
    validates :content_85
    validates :content_86
    validates :content_87
    validates :content_88
    validates :content_89
    validates :content_90
    validates :content_91
    validates :content_92
    validates :content_93
    validates :content_94
    validates :content_95
    validates :content_96
    validates :content_97
    validates :content_98
    validates :content_99
    validates :content_100
  end
  with_options length: { maximum: 20 } do
    validates :head_1
    validates :head_2
    validates :head_3
    validates :head_4
    validates :head_5
    validates :head_6
    validates :head_7
    validates :head_8
    validates :head_9
    validates :head_10
    validates :head_11
    validates :head_12
    validates :head_13
    validates :head_14
    validates :head_15
    validates :head_16
    validates :head_17
    validates :head_18
    validates :head_19
    validates :head_20
    validates :head_21
    validates :head_22
    validates :head_23
    validates :head_24
    validates :head_25
    validates :head_26
    validates :head_27
    validates :head_28
    validates :head_29
    validates :head_30
    validates :head_31
    validates :head_32
    validates :head_33
    validates :head_34
    validates :head_35
    validates :head_36
    validates :head_37
    validates :head_38
    validates :head_39
    validates :head_40
    validates :head_41
    validates :head_42
    validates :head_43
    validates :head_44
    validates :head_45
    validates :head_46
    validates :head_47
    validates :head_48
    validates :head_49
    validates :head_50
    validates :head_51
    validates :head_52
    validates :head_53
    validates :head_54
    validates :head_55
    validates :head_56
    validates :head_57
    validates :head_58
    validates :head_59
    validates :head_60
    validates :head_61
    validates :head_62
    validates :head_63
    validates :head_64
    validates :head_65
    validates :head_66
    validates :head_67
    validates :head_68
    validates :head_69
    validates :head_70
    validates :head_71
    validates :head_72
    validates :head_73
    validates :head_74
    validates :head_75
    validates :head_76
    validates :head_77
    validates :head_78
    validates :head_79
    validates :head_80
    validates :head_81
    validates :head_82
    validates :head_83
    validates :head_84
    validates :head_85
    validates :head_86
    validates :head_87
    validates :head_88
    validates :head_89
    validates :head_90
    validates :head_91
    validates :head_92
    validates :head_93
    validates :head_94
    validates :head_95
    validates :head_96
    validates :head_97
    validates :head_98
    validates :head_99
    validates :head_100
  end

  scope :created_at_limit,
    -> { order('id desc').limit(5) }

  scope :favorites_order,
  -> { order('favs desc') }


  ransacker :favorites_count do
    query = '(SELECT COUNT(favorites.answer_id) FROM favorites where favorites.answer_id = answers.id GROUP BY favorites.answer_id)'
    Arel.sql(query)
  end

private
  def image_or_select
    image.present? || select_image.present?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :q_find, only: [:new, :create]
  before_action :a_find, only: [:show, :edit, :update, :destroy]
  before_action :content_set, :head_set, :question_set
  before_action :a_content_post_set, only: [:show, :edit, :update]
  before_action :q_content_post_set, only: [:new, :create]
  before_action :thumbnail, only: [:show, :edit, :update]
  before_action :a_question_set, only: [:show, :edit, :update]
  before_action :a_head_post_set, only: [:show, :edit, :update]

  def index
    @search = Answer.ransack(params[:q])
    @as = @search.result.page(params[:page]).per(12)
  end

  def show
    description(@a,200)
    if @a.image.present?
      @twitter_card = @a.image
    else 
      @twitter_card = 'https://res.cloudinary.com/hgxti2nqv/image/upload/v1/' + @a.select_image
    end
  end

  def new
    if user_signed_in?
      @a = current_user.answers.new
      @select_image = image
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @a = current_user.answers.new(a_params)
    @select_image = image
    if params[:back].present?
      render :new
      return
    end

    if @a.save
      redirect_to a_show_url(@a)
    else
      render :new
    end
  end

  def edit
    if @a.user == current_user
      @select_image = image
    else
      redirect_to new_user_session_path
    end
  end

  def update
    @select_image = image
    if @a.update_attributes(a_params)
      if @a.saved_change_to_select_image?
        @a.update_attributes( image: "")
      end
      redirect_to a_show_url(@a)
    else
      render :edit
    end
  end

  def destroy
    if @a.user == current_user
      @a.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

    # if @a.saved_change_to_image?
    #   @a.select_image = ''
    #   @a.save
    # else @a.seved_change_to_select_image?
    #   @a.image.destroy
    # end

  private
  def a_params
    params.require(:answer).permit(:title, :answerer, :overview, @content_array, @head_array, @question_array, :image, :image_cache, :select_image, :question_id, :tag_list)
  end

  def q_find
    @q = Question.find_by(public_uid: params[:id])
  end

  def a_find
    @a = Answer.find_by(public_uid: params[:id])
  end

  def image 
    a = []
    for i in 1..18 do
      a.push('free_image/' + i.to_s + '.jpg')
    end
    for i in 1..2 do
      a.push('free_image/p' + i.to_s + '.png')
    end
    return a
  end

end

app/views/answers/confirm.html.slim
.container
  = form_for @a, url:a_create_path do |f|
    .row
      .col-md-10.offset-md-1.form-group
        h4.text-center 投稿確認
        .border-bottom.article-border
        h1.mb-2 = @a.title
        = f.hidden_field :title
        = cl_image_tag(@thumbnail, class:'img-fluid mb-3')
        = image_tag  (@a.image.url)
        = f.text_field :image_cache
        = f.hidden_field :select_image
        p
          = @a.overview
          = f.hidden_field :overview
          = f.hidden_field :answerer
        - @q_content_post.each_with_index do |x, i|
          - if @a_head_post[i].present?
            h3.under = @a_head_post[i]
          p
            strong --#{x}
          p.mb-4
            - if @a.answerer.present?
              font.mr-2 color="red"
                = @a.answerer
            = @a_content_post[i]
        - @content_array.each_with_index do |x, i|
          = f.hidden_field @head_array[i]
          = f.hidden_field x
        - if @a.tag_list.present?
          h5.mb-5
            - @a.tag_list.each do |tag|
              span.badge.badge-primary.mr-2
                = tag      
              = f.hidden_field :tag_list, value: @a.tag_list.join(',')
        = f.hidden_field :question_id
        = f.submit '戻る', name: 'back', class: 'btn btn-secondary btn-lg mr-3'
        = f.submit '投稿', class: 'btn btn-success btn-lg'

app/views/answers/edit.html.slim
= stylesheet_pack_tag 'a_new'
#App.container
  = form_with model: @a, local: true, url: a_update_path do |f|
    = render 'layouts/error_messages', model: f.object 
    .row
      .col-md-10.offset-md-1.form-group
        .row
          .col-md-2
            = f.label :title, 'タイトル'
            small
              span.badge.badge-danger 必須
          .col-md-10
            = f.text_field :title, class: 'form-control', "v-model" => "title"
            text-count :text="title" :limit="50"
            p#initial_title(style="display: none;") = @a.title
          .col-12.border-bottom.article-border
          .col-md-2
            = f.label :answerer, '回答者'
          .col-md-10
            = f.text_field :answerer, class: 'form-control', "v-model" => "answerer"
            text-count :text="answerer" :limit="10"
            p#initial_answerer(style="display: none;") = @a.answerer
          .col-12.border-bottom.article-border
          .col-md-2
            = f.label :overview, '概要'
          .col-md-10
            = f.text_area :overview, class: 'form-control', "v-model" => "overview"
            text-count :text="overview" :limit="1000"
            p#initial_overview(style="display: none;") = @a.overview
          .col-12.border-bottom.article-border
          .col-12
            = f.label :image, 'サムネイル'
            br
            button.btn.btn-info.mr-4 type="button" @click="free_image = true; up_image = true" :disabled="free_image" フリー素材から選ぶ
            button.btn.btn-info type="button" @click="free_image = false; up_image = false" :disabled="!up_image" アップロードする
            / ここからフリー素材
            .free_image.mt-2 v-if="free_image"
              - @select_image.each_with_index do |x, i|
                - if @select_image.length/2 === i
                  br
                label
                  = f.radio_button :select_image, x, class:'image-radio', "v-on:click" => "reset()", "v-model" => "radio_reset"
                  span
                    = cl_image_tag(x, width: 150, crop: :fill, class: 'image')
            / フリー素材ここまで
            = f.file_field :image, class: 'form-control-file mt-2', "v-bind:disabled" => "up_image", "ref" => "file"
            - @a_question_post.compact.reject(&:empty?).each_with_index do |x, i|
              .border-bottom(style="margin: 10px 0;")
              span.badge.badge-info.head @click="changehead(#{i})" 
                - if i === 0 
                  | 見出しを追加する>>
                - else 
                  | >>
              div v-show="head_show[#{i}]"
                = f.text_field @head_array[i], class: 'form-control', "v-model" => "head[#{i}]"
                text-count :text="head[#{i}]" :limit="20"
              p
                b --#{x}
              = f.text_area @content_array[i], class: 'form-control', "v-model" => "content[#{i}]"
              text-count :text="content[#{i}]" :limit="255"
          .col-12.border-bottom.article-border
          .col-md-2
              = f.label :tag_list, 'タグ'
          .col-md-10
              = f.text_field :tag_list, value: @a.tag_list.join(','), class: "form-control"
              small 半角コンマで区切って入力(例：ゲーム,アニメ,キャラクター)
          .col-12.mt-3
            = f.submit "投稿する", class:"btn btn-secondary btn-block mb-3"
        .text-right.mt-5
          = link_to "記事を削除する", a_destroy_path, method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-outline-danger btn-sm"
          .initial-content
            - @a_content_post.each_with_index do |x, i|
              p id="initial_head_#{i}" style="display: none;" = @a_head_post[i]
              p id="initial_content_#{i}" style="display: none;" = x
= javascript_pack_tag 'a_edit.js'

app/views/answers/index.html.slim
.container
    .row
        .col-md-10.offset-md-1
            .row
                .col-md-4.order-md-2.text-right.text-nowrap.mb-4
                    span.btn-group.mr-3
                        - if params.dig(:q, :created_at_gteq).present?
                            = link_to '最近',{:controller=>"answers",:action=>"index",:q=>{:created_at_gteq => 30.day.ago.all_day, :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :sorts => params.dig(:q, :sorts)}}, class:'btn btn-info'
                            = link_to '全部',{:controller=>"answers",:action=>"index",:q=>{:created_at_gteq => '', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :sorts => params.dig(:q, :sorts)}}, class:'btn btn-outline-info'
                        - else
                            = link_to '最近',{:controller=>"answers",:action=>"index",:q=>{:created_at_gteq => 30.day.ago.all_day, :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :sorts => params.dig(:q, :sorts)}}, class:'btn btn-outline-info'
                            = link_to '全部',{:controller=>"answers",:action=>"index",:q=>{:created_at_gteq => '', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :sorts => params.dig(:q, :sorts)}}, class:'btn btn-info'
                    span.btn-group
                        - if params.dig(:q, :sorts) === 'favorites_count desc'
                            = link_to '人気順',{:controller=>"answers",:action=>"index",:q=>{:sorts => 'favorites_count desc', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont),:created_at_gteq => params.dig(:q, :created_at_gteq)}}, class:'btn btn-info'
                            = link_to '新着順',{:controller=>"answers",:action=>"index",:q=>{:sorts => 'id desc', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :created_at_gteq => params.dig(:q, :created_at_gteq)}}, class:'btn btn-outline-info'
                        - else
                            = link_to '人気順',{:controller=>"answers",:action=>"index",:q=>{:sorts => 'favorites_count desc', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont),:created_at_gteq => params.dig(:q, :created_at_gteq)}}, class:'btn btn-outline-info'
                            = link_to '新着順',{:controller=>"answers",:action=>"index",:q=>{:sorts => 'id desc', :title_or_tags_name_cont => params.dig(:q, :title_or_tags_name_cont), :created_at_gteq => params.dig(:q, :created_at_gteq)}}, class:'btn btn-info'
                .col-md-8.order-md-1.mb-4
                    = search_form_for @search, url:answers_path do |f|
                        = f.search_field :created_at_gteq, value: params.dig(:q, :created_at_gteq), class: 'form-control', style: 'display: none;'
                        = f.search_field :sorts, value: params.dig(:q, :sorts), class: 'form-control', style: 'display: none;'
                        .input-group
                            = f.search_field :title_or_tags_name_cont, value: params.dig(:q, :title_or_tags_name_cont), class: 'form-control'
                            span.input-group-btn
                                = f.submit '検索', class: 'btn btn-info'
            == render './posts/a_posts', posts: @as
            - unless @as.present?
                .alert.alert-secondary 検索結果はありませんでした
            .border-bottom.article-border.mt-3.mb-5
            = paginate @as

app/views/answers/new.html.slim
= stylesheet_pack_tag 'a_new'
#App.container
  = form_with model: @a, local: true, url: a_create_path do |f|
    = render 'layouts/error_messages', model: f.object
    .row
      .col-md-10.offset-md-1.form-group
        .row
          .col-md-2
            = f.label :title, 'タイトル'
            small
              span.badge.badge-danger 必須
          .col-md-10
            = f.text_field :title, class: 'form-control', "v-model" => "title"
            text-count :text="title" :limit="50"
            p#initial_title(style="display: none;") = @a.title
          .col-12.border-bottom.article-border
          .col-md-2
            = f.label :answerer, '回答者'
          .col-md-10
            = f.text_field :answerer, class: 'form-control', "v-model" => "answerer"
            text-count :text="answerer" :limit="10"
            small 
              |※回答の前に名前を追加できます。(例:　
              span.text-danger たかし
              |　そうですね。)
            p#initial_answerer(style="display: none;") = @a.answerer
          .col-12.border-bottom.article-border
          .col-md-2
            = f.label :overview, '概要'
          .col-md-10
            = f.text_area :overview, class: 'form-control', "v-model" => "overview"
            text-count :text="overview" :limit="1000"
            p#initial_overview(style="display: none;") = @a.overview
          .col-12.border-bottom.article-border
          .col-12
            = f.label :image, 'サムネイル'
            br
            button.btn.btn-info.mr-4 type="button" @click="free_image = true; up_image = true" :disabled="free_image" フリー素材から選ぶ
            button.btn.btn-info type="button" @click="free_image = false; up_image = false" :disabled="!up_image" アップロードする
            / ここからフリー素材
            .free_image.mt-2 v-if="free_image"
              - @select_image.each_with_index do |x, i|
                - if @select_image.length/2 === i
                  br
                label
                  = f.radio_button :select_image, x, class:'image-radio', "v-on:click" => "reset()"
                  span
                    = cl_image_tag(x, width: 150, crop: :fill, class: 'image')
            / フリー素材ここまで
            = f.file_field :image, class: 'form-control-file mt-2', "v-bind:disabled" => "up_image", "ref" => "file"
            - @q_content_post.each_with_index do |x, i|
              .border-bottom(style="margin: 10px 0;")
              span.badge.badge-info.head @click="changehead(#{i})" 
                - if i === 0 
                  | 見出しを追加する>>
                - else 
                  | >>
              div v-show="head_show[#{i}]"
                = f.text_field @head_array[i], class: 'form-control', "v-model" => "head[#{i}]"
                text-count :text="head[#{i}]" :limit="20"
              p
                b --#{x}
              = f.hidden_field @question_array[i], value: x
              = f.text_area @content_array[i], class: 'form-control', "v-model" => "content[#{i}]"
              text-count :text="content[#{i}]" :limit="255"
          .col-12.border-bottom.article-border
          .col-md-2
              = f.label :tag_list, 'タグ'
          .col-md-10
              = f.text_field :tag_list, value: @a.tag_list.join(','), class: "form-control"
              small 半角コンマで区切って入力(例：ゲーム,アニメ,キャラクター)
          .col-12.mt-3
            = f.hidden_field :question_id, value: @q.id
            = f.submit "投稿する", class:"btn btn-secondary btn-block mb-3"
            - @a_content_post.present?
              - @a_content_post.each_with_index do |x, i|
                p id="initial_head_#{i}" style="display: none;" = @a_head_post[i]
                p id="initial_content_#{i}" style="display: none;" = x
= javascript_pack_tag 'a_new.js'

app/views/answers/show.html.slim
- set_meta_tags title: @a.title,
    og: {   site_name: 'intervieeew.net',
            title: @a.title,
            description: @description,
            type: 'website',
            url: request.original_url,
            locale: 'ja_JP',
            image: @twitter_card},
    twitter: {card: 'summary_large_image',
        }
.container
    .row
        .col-md-10.offset-md-1
            - if user_signed_in?
                - if current_user.id === @a.user.id
                    .text-right.mb-4
                        = link_to "編集する", a_edit_path(@a.public_uid), class: 'btn btn-outline-secondary'
            .d-flex.justify-content-between
                == render './favorites/favorite'
                a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false" Tweet
                script[async src="https://platform.twitter.com/widgets.js" charset="utf-8"]
            h1.mb-4 = @a.title
            = cl_image_tag(@thumbnail, class:'img-fluid mb-3')
            p
                = @a.overview
            - @a_question_post.compact.reject(&:empty?).each_with_index do |x, i|
                - if @a_head_post[i].present?
                    h3.under = @a_head_post[i]
                p.mt-4
                    strong --#{x}
                p
                - if @a.answerer.present?
                    font.mr-2 color="red"
                        = @a.answerer
                = @a_content_post[i]
            - if @a.tag_list.present?
                h5.mb-5
                - @a.tag_list.each do |tag|
                    = link_to :controller=>"answers",:action=>"index",:q=>{:title_or_tags_name_cont => tag, :sorts => 'id desc'} do
                        span.badge.badge-info.mr-2
                            i.fas.fa-tag
                            = tag
            .border-bottom.article-border
            .d-flex.justify-content-between.mb-3
                = link_to user_path(@a.user.public_uid)
                    p 投稿者:#{@a.user.username}
                .text-dark
                    i.fas.fa-clock
                    = l @a.created_at, format: :long
            - if @a.question.present?
                = link_to q_show_path(@a.question.public_uid),class:'text-decoration-none text-dark' do 
                    .card
                        .card-header
                            | この投稿の質問
                        .card-body
                            h5.card-title
                                = @a.question.title
                            p.card-text
                                = [@a.question.content_1,@a.question.content_2,@a.question.content_3,@a.question.content_4,@a.question.content_5,@a.question.content_6,@a.question.content_7,@a.question.content_8,@a.question.content_9,@a.question.content_10].compact.reject(&:empty?).join(',').truncate(200)
                            - if @a.question.tag_list.present?
                                p
                                    span.badge.badge-primary
                                        i.far.fa-question-circle
                                        = @a.question.tag_list.first
            - else
                .alert.alert-secondary 質問は削除されました
                    