config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations' } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  get 'toppages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show]
  get '/users/:id/a', to:'users#answers', as: 'users_a'
  get '/users/:id/q', to:'users#questions', as: 'users_q'
  get '/users/:id/fav', to:'users#favorites', as: 'users_f'
  get '/questions', to:'questions#index'
  get '/q/new', to: 'questions#new'
  post '/q/confirm', to: 'questions#confirm'
  post '/q', to: 'questions#create', as: 'qs'
  get '/q/:id', to: 'questions#show', as: 'q_show'
  get '/q/edit/:id', to: 'questions#edit', as: 'q_edit'
  patch '/q/edit/:id', to: 'questions#update', as: 'q_update'
  delete '/q/:id', to: 'questions#destroy', as: 'q_destroy'
  # get '/a', to:'answers#index'
  get '/:id/a', to: 'answers#new', as: 'a_new'
  post '/:id/a_confirm', to: 'answers#confirm', as: 'a_confirm'
  post '/:id/a', to: 'answers#create', as: 'a_create'
  get '/a/:id', to: 'answers#show', as: 'a_show'
  get '/a/edit/:id', to: 'answers#edit', as: 'a_edit'
  patch '/a/edit/:id', to: 'answers#update', as: 'a_update'
  delete '/a/:id', to: 'answers#destroy', as: 'a_destroy'
  # post '/a/:id/favorites', to: 'favorites#create', as: 'favorite_create'
  # delete '/a/:id/favorites', to: 'favorites#destroy', as: 'favorite_destroy'
  resources :answers, only: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
end

app/views/posts/_a_posts.html.slim
- posts.each_with_index do |a,i|
    = link_to a_show_path(a.public_uid), class:'text-decoration-none' do
        article.article.d-flex.flex-nowrap
            .article-image.mr-2
                - if a.image.present?
                    = cl_image_tag(a.image, width: 180, height: 180,  crop: :fill, class:'')
                - else 
                    = cl_image_tag(a.select_image, width: 180, height: 180,  crop: :fill, class:'')
            .align-self-center.d-flex.flex-column
                h4.article-title = a.title
                - if a.overview.present?
                    p.text-dark = a.overview.truncate(50)
                .d-flex.flex-wrap
                    - if a.tag_list.present?
                        span.badge.badge-info.mr-5
                            i.fas.fa-tag
                            = a.tag_list.first.truncate(15)
                    span.small.mr-5 style="color: goldenrod;"
                        i.fas.fa-star.mr-1
                        = a.favorites.length
                    span.small.text-dark.mr-5
                        i.fas.fa-user-circle
                        = a.user.username
                    span.small.text-dark
                        i.fas.fa-clock
                        = l a.created_at, format: :long
    - unless i == posts.length - 1
        .border-bottom.article-border.mt-3.mb-3
    

app/views/posts/_a_tags.html.slim
 - if a_tag.present?
    p.article-tag
        - a_tag.each do |tag|
            span.badge.badge-info
                i.fas.fa-tag
                = tag

app/views/posts/_q_posts.html.slim
- posts.each_with_index do |q,i|
    = link_to q_show_path(q.public_uid), class:'text-decoration-none' do
        article
            h3.article-title = q.title
            ul.text-dark
                li = q.content_1.truncate(20)
                li = q.content_2.truncate(20)
                li = q.content_3.truncate(20)
            .d-flex.flex-wrap
                - if q.tag_list.present?
                        span.badge.badge-primary.mr-5
                            i.far.fa-question-circle
                            = q.tag_list.first.truncate(15)
                span.small.mr-5 style="color: green;"
                    i.fas.fa-reply.mr-1
                    = q.answers.length
                span.small.text-dark.mr-5
                    i.fas.fa-user-circle
                    = q.user.username
                span.small.text-dark
                    i.fas.fa-clock
                    = l q.created_at, format: :long
    - unless i == posts.length - 1
        .border-bottom.article-border.mt-3.mb-3
    