config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations' } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  get 'toppages/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:show]
  get '/users/:id/a', to:'users#answers', as: 'users_a'
  get '/users/:id/q', to:'users#questions', as: 'users_q'
  get '/users/:id/fav', to:'users#favorites', as: 'users_f'
  get '/questions', to:'questions#index'
  get '/q/new', to: 'questions#new'
  post '/q/confirm', to: 'questions#confirm'
  post '/q', to: 'questions#create', as: 'qs'
  get '/q/:id', to: 'questions#show', as: 'q_show'
  get '/q/edit/:id', to: 'questions#edit', as: 'q_edit'
  patch '/q/edit/:id', to: 'questions#update', as: 'q_update'
  delete '/q/:id', to: 'questions#destroy', as: 'q_destroy'
  # get '/a', to:'answers#index'
  get '/:id/a', to: 'answers#new', as: 'a_new'
  post '/:id/a_confirm', to: 'answers#confirm', as: 'a_confirm'
  post '/:id/a', to: 'answers#create', as: 'a_create'
  get '/a/:id', to: 'answers#show', as: 'a_show'
  get '/a/edit/:id', to: 'answers#edit', as: 'a_edit'
  patch '/a/edit/:id', to: 'answers#update', as: 'a_update'
  delete '/a/:id', to: 'answers#destroy', as: 'a_destroy'
  # post '/a/:id/favorites', to: 'favorites#create', as: 'favorite_create'
  # delete '/a/:id/favorites', to: 'favorites#destroy', as: 'favorite_destroy'
  resources :answers, only: [:index] do
    resource :favorites, only: [:create, :destroy]
  end
end

app/views/layouts/_error_messages.html.slim
- if model.errors.any?
  #error_explanation.alert.alert-warning
    ul.mb-0
      - model.errors.full_messages.each do |message|
        li= message

app/views/layouts/_navbar.html.slim
.fluid-container
  .d-flex.justify-content-around.flex-nowrap
    .d-none.d-sm-inline-block
      = link_to root_path, class:'text-decoration-none' do
        h1.text-dark intervieeew.net
    .d-none.d-sm-inline-block
      
      span
        = search_form_for @search, url:answers_path, class:'form-inline', style: 'display: inline-block;' do |f|
          a href ="https://twitter.com/intervieeew" target="_blank"
            i.fab.fa-twitter.fa-2x.mt-1.ml-4
          = f.button :type => "submit", class:'bg-white', style: 'border-style: none;' do
            i.fas.fa-search.fa-lg.mt-2
          = f.search_field :sorts, value: 'id desc', class: 'form-control', style: 'display: none;'
          = f.search_field :title_or_tags_name_cont, value: params.dig(:q, :title_or_tags_name_cont), id: 'navbar-search', class: 'form-control mt-2', placeholder:'記事を検索'
nav.navbar.navbar-expand-sm.navbar-light.bg-info.mb-5
  a.navbar-brand.d-block.d-sm-none.center-align.text-light intervieeew.net
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse.justify-content-center
    ul.navbar-nav.row
      li.nav-item.col-sm-3.col-lg-2.offset-lg-2.text-center = link_to '見る', answers_path(q: { created_at_gteq: 30.day.ago.all_day, sorts: 'favorites_count desc' }), class: 'nav-link text-light'
      li.nav-item.col-sm-3.col-lg-2.text-center = link_to '答える', questions_path(q: { created_at_gteq: 30.day.ago.all_day, sorts: 'reply_count desc' }), class: 'nav-link text-light'
      li.nav-item.col-sm-3.col-lg-2.text-center = link_to '質問する', q_new_path, class: 'nav-link text-light'
      - if user_signed_in?
        li.nav-item.col-sm-3.col-lg-2.text-center = link_to 'マイページ', user_path(current_user.public_uid), class: 'nav-link text-light'
      - else
        li.nav-item.col-sm-3.col-lg-2.text-center = link_to 'ログイン', new_user_session_path, class: 'nav-link text-light' 

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = csp_meta_tag
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    /! Global site tag (gtag.js) - Google Analytics
    script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-177194522-2" 
    javascript:
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-177194522-2');
  body
    = render 'layouts/navbar'
    = yield